databases:
  - name: postgres
    ipAllowList: []
    databaseName: Collabz_test
    user: master

services:
  - type: web
    name: Collabz
    env: ruby
    buildCommand: "./render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
